# docker-compose.yml
version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    ports:
      - "8000:8000" # 對應主機的8000端口到容器的8000端口
    volumes:
      - .:/app                # 掛載原始碼
      - ./.env:/app/.env      #掛載 .env 進容器
    environment:
      - FLASK_APP=line_bot_server.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=8000
    command: flask run --host=0.0.0.0 --port=8000